소셜 게시글과 루틴 연동
toduck-App/toduck-backend pull request #31
Opened 2024-11-29 08:49 UTC by Junad-Park

## ✨ 작업 내용

**1️⃣ 소셜 게시글과 루틴 연동**
```SQL
CREATE TABLE social
(
    ...
    routine_id   BIGINT       NULL,
    ...
    FOREIGN KEY (routine_id) REFERENCES routine (id)
);
```
- 소셜 게시글 생성, 수정, 조회 시 루틴 정보를 연동하도록 기능을 구현

  <br/>

**2️⃣ 데이터베이스 초기화 순서 수정**

**변경 전:**
```SQL
INSERT INTO social (...) VALUES (...);
INSERT INTO routine (...) VALUES (...);
```

**변경 후:**
```SQL
INSERT INTO routine (...) VALUES (...);
INSERT INTO social (...) VALUES (...);
```
  <br/>

## ✅ 리뷰 요구사항

- 루틴 연동 관련 코드 개선이 필요한 부분이 있는지 확인 부탁드립니다.
- 특히, 게시글 수정 시 `routineId`가 `null`인 경우 변경 없음 `0`인 경우 제거, `유효한 Id` 인 경우 루틴 수정 처리가 올바르게 구현되었는지 확인 부탁드립니다.

2024-11-29 16:52 UTC, Seol-JY requested changes
고생하셨습니다~!

2024-11-29 16:52 UTC, Seol-JY commented on src/main/java/im/toduck/domain/social/domain/usecase/SocialBoardUseCase.java
> +		}
p2: 사용자 루틴을 저장하기 위해 루틴 정보를 불러오는 부분으로 보이는데요. 비공개 루틴도 저장할 수 없으니 이 점도 고려하는 것이 좋아 보입니다!  routineService와 routineRepository에 메서드를 추가해서 구현하면 될 것 같습니다! 아래 게시글 수정의 루틴 블러오는 과정에서도 같은 처리 부탁드려요!

2024-11-29 16:52 UTC, Seol-JY commented on src/main/java/im/toduck/domain/social/domain/usecase/SocialBoardUseCase.java
> +		if (routineId == null || routineId == 0) {
p5: `routineId == 0`은 어떤 경우인가요?

2024-11-29 16:52 UTC, Seol-JY commented on src/test/java/im/toduck/domain/social/domain/usecase/SocialBoardUseCaseTest.java
p5: 테스트 수정.. 고생하셨습니다..!

2024-11-29 16:58 UTC, Junad-Park commented on src/main/java/im/toduck/domain/social/domain/usecase/SocialBoardUseCase.java
> +		if (routineId == null || routineId == 0) {
@Seol-JY 리뷰 요구사항에 적어 놓은데로 null은 변경사항 없음 0은 공유할 루틴 제거 입니다!

2024-11-29 17:00 UTC, Junad-Park commented on src/main/java/im/toduck/domain/social/domain/usecase/SocialBoardUseCase.java
> +		}
@Seol-JY 좋은 지적 감사합니다! 수정하겠습니다

2024-11-30 05:36 UTC, kang20 commented on src/main/java/im/toduck/domain/social/domain/usecase/SocialBoardUseCase.java
>  	}
p4: 이부분도 위에 review 에서 언급된거와 같이 공개 여부를 판단해서 예외 처리 해야할거 같습니다

2024-11-30 05:36 UTC, kang20 commented on src/main/java/im/toduck/domain/social/domain/usecase/SocialBoardUseCase.java
> +		if (routineId == null || routineId == 0) {
p5: routineId 를 0인지 검사하여 공유 루틴을 제거하는 것이 로직상 이상이 없지만 그래도 0이라는 상수 자체가 의미를 내포하는것이 떨어진다고 생각합니다 차라리 isRemoveRoutine 같은 boolean 형태로 검사하는 것이 의미적으로 좋다고 생각하는데 어떻게 생각하시나요?

2024-12-02 14:32 UTC, Junad-Park commented on src/main/java/im/toduck/domain/social/domain/usecase/SocialBoardUseCase.java
> +		if (routineId == null || routineId == 0) {
@kang20 아, `isRemoveRoutine`을 생각하지 못했네요! 감사합니다 ! 훨씬 좋은 것 같습니다👍

2024-12-05 09:39 UTC, Seol-JY approved these changes

2024-12-06 08:50 UTC, kang20 approved these changes
리뷰 내용 잘 반영해주셨네요 고생하셨습니다!

2024-12-06 08:52 UTC, merged