소셜 게시글 카테고리별 정렬 및 카테고리 목록 조회 API 개발
toduck-App/toduck-backend pull request #34
Opened 2024-12-07 19:10 UTC by Junad-Park

## ✨ 작업 내용

**1️⃣ 소셜 게시글 카테고리별 정렬 기능 추가**
- 기존에 있던 게시글 목록 조회에 카테고리별 정렬 기능 추가

![스크린샷 2024-12-08 오전 4 07 18](https://github.com/user-attachments/assets/2b2b7337-1d4a-4742-9b17-815889cf36f2)

  <br/>

**2️⃣ 카테고리 목록 조회 기능 추가**
- 해당 프로젝트에 있는 모든 카테고리 정보를 조회

  <br/>

## ✅ 리뷰 요구사항
- 궁금한 점이 있다면 댓글 남겨주세요!

2024-12-08 18:24 UTC, Seol-JY requested changes
고생하셨습니다~! 리뷰 확인해주세용

2024-12-08 18:24 UTC, Seol-JY commented on src/main/java/im/toduck/domain/social/domain/service/SocialBoardService.java
>  	}
p4: `findAllById` 수행 시 socialCategoryIds에 존재하지 않은 카테고리 id가 있을 경우 별도 예외가 발생하지 않나요?

2024-12-08 18:24 UTC, Seol-JY commented on src/main/java/im/toduck/domain/social/domain/usecase/SocialBoardUseCase.java
>  	}
p3: [해당 부분](https://github.com/toduck-App/toduck-backend/pull/34/files#diff-0f72d2dfcec078cd1b9ee766bb089ebad0b2331228f88e7cb3b75219128468fbR186-R190) 에서 내부적으로 카테고리 유효성 검사를 수행하고 있는 것으로 보이는데, 실제 카테고리를 찾는 부분을 Usecase에서 우선 찾고 게시글을 조회하도록 하면 예외 처리를 조금 더 명확하게 표현할 수 있을 것으로 보이는데 어떻게 생각하시나요?! 

만일 기존 방식대로 내부적으로 처리하는 경우에는, 예외가 발생할 수 있는 부분이 getSocials 뿐이라면 예외 처리 범위를 줄여도 좋다는 생각이 드는데, 혹시 다른 부분에서도 발생이 예상되는 부분이 있을까요?

2024-12-08 18:28 UTC, Junad-Park commented on src/main/java/im/toduck/domain/social/domain/service/SocialBoardService.java
>  	}
@Seol-JY `JPA`의 `findAllById` 메서드는 존재하지 않는`ID`에 대해 별도의 예외를 발생시키지 않습니다!

2024-12-08 18:47 UTC, Junad-Park commented on src/main/java/im/toduck/domain/social/domain/usecase/SocialBoardUseCase.java
>  	}
@Seol-JY 요청받은 `categoryIds`와 그것으로 찾은 `소셜 카테고리의 개수`를 체크해 유효하지 않은 카테고리를 확인하는 함수를  `SocialBoardService` 에서 여러군데 사용중이어서 홀린듯이 작성했네요..! 예외 처리를 더 명확하게 표현할 수 있도록 수정하겠습니다!

2024-12-15 20:58 UTC, Seol-JY approved these changes
LGTM!

2024-12-22 05:52 UTC, kang20 approved these changes
너무 늦게 승인해서 죄송합니다 고생하셨습니다!

2025-01-03 15:47 UTC, merged